import Ionicons from '@expo/vector-icons/Ionicons';
import React, { useState } from 'react';
import { Modal, Pressable, ScrollView, StyleSheet, TextInput, View } from 'react-native';

import { PublicUser, socialApi } from '../features/social/api';
import { useAppTheme } from '../theme/ThemeProvider';
import { AppText } from './AppText';

type Props = { visible: boolean; token: string; onClose: () => void };
export function UserSearchModal({ visible, token, onClose }: Props) {
  const { colors, radius } = useAppTheme();
  const [query, setQuery] = useState(''); const [users, setUsers] = useState<PublicUser[]>([]); const [selected, setSelected] = useState<(PublicUser & { followers?: number; following?: number; publicHabits?: { id: string; name: string }[] }) | null>(null);
  const search = async (value: string) => { setQuery(value); if (!value.trim()) return setUsers([]); try { setUsers(await socialApi.searchUsers(token, value)); } catch { setUsers([]); } };
  const open = async (user: PublicUser) => { try { setSelected(await socialApi.profile(token, user.id)); } catch { setSelected(null); } };
  const toggleFollow = async () => { if (!selected) return; const following = !selected.isFollowing; try { following ? await socialApi.follow(token, selected.id) : await socialApi.unfollow(token, selected.id); setSelected({ ...selected, isFollowing: following, followers: (selected.followers ?? 0) + (following ? 1 : -1) }); } catch { /* Retry remains available. */ } };
  return <Modal transparent visible={visible} animationType="slide" onRequestClose={onClose}><View style={styles.overlay}><View style={[styles.sheet, { backgroundColor: colors.surface, borderTopLeftRadius: radius.xl, borderTopRightRadius: radius.xl }]}><View style={styles.header}><AppText variant="heading" weight="800">Buscar personas</AppText><Pressable onPress={onClose}><Ionicons name="close" size={24} color={colors.textSecondary} /></Pressable></View>{selected ? <ScrollView><Pressable onPress={() => setSelected(null)}><AppText color={colors.primary}>‹ Volver a resultados</AppText></Pressable><AppText variant="title" weight="800" style={styles.name}>{selected.displayName}</AppText><AppText color={colors.textSecondary}>@{selected.username}</AppText><AppText variant="small" style={styles.bio}>{selected.bio || 'Sin biografía todavía.'}</AppText><AppText variant="small" weight="700">{selected.followers ?? 0} seguidores · {selected.following ?? 0} seguidos</AppText><Pressable onPress={() => void toggleFollow()} style={[styles.follow, { backgroundColor: selected.isFollowing ? colors.surfaceMuted : colors.primary, borderRadius: radius.full }]}><AppText weight="800" color={selected.isFollowing ? colors.text : colors.white}>{selected.isFollowing ? 'Siguiendo' : 'Seguir'}</AppText></Pressable><AppText weight="800" style={styles.publicTitle}>Hábitos públicos</AppText>{selected.publicHabits?.map((habit) => <AppText key={habit.id} style={styles.habit}>• {habit.name}</AppText>)}</ScrollView> : <><TextInput autoFocus value={query} onChangeText={(value) => void search(value)} placeholder="Busca por nombre o usuario" placeholderTextColor={colors.textSecondary} style={[styles.input, { color: colors.text, borderColor: colors.border, borderRadius: radius.md }]} /><ScrollView keyboardShouldPersistTaps="handled">{users.map((user) => <Pressable key={user.id} onPress={() => void open(user)} style={[styles.user, { borderBottomColor: colors.border }]}><View style={[styles.avatar, { backgroundColor: colors.primarySoft }]}><AppText weight="800" color={colors.primary}>{user.displayName.slice(0, 1)}</AppText></View><View><AppText weight="800">{user.displayName}</AppText><AppText variant="small" color={colors.textSecondary}>@{user.username}</AppText></View></Pressable>)}</ScrollView></>}</View></View></Modal>;
}
const styles = StyleSheet.create({ overlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,.35)' }, sheet: { maxHeight: '88%', minHeight: '68%', padding: 22 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }, input: { minHeight: 50, borderWidth: 1, paddingHorizontal: 13 }, user: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 13, borderBottomWidth: StyleSheet.hairlineWidth }, avatar: { width: 42, height: 42, borderRadius: 15, alignItems: 'center', justifyContent: 'center' }, name: { marginTop: 20 }, bio: { marginVertical: 12 }, follow: { alignSelf: 'flex-start', paddingHorizontal: 18, paddingVertical: 10, marginTop: 16 }, publicTitle: { marginTop: 24, marginBottom: 8 }, habit: { paddingVertical: 5 } });
